# Generated by Django 5.2.6 on 2026-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='title',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume_file',
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
