# Generated by Django 5.2.6 on 2026-02-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', max_length=10),
        ),
    ]
