# Generated by Django 6.0.1 on 2026-02-05 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_type_consultantmeeting'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantmeeting',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='consultantmeeting',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='consultantmeeting',
            name='job_application',
        ),
        migrations.AddField(
            model_name='consultantmeeting',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='jobs.jobapplication'),
        ),
    ]
