# Generated by Django 5.2.6 on 2026-02-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('features', models.TextField(help_text='Comma separated (Eg: 100% Job Assistance, Live Classes)')),
                ('image', models.ImageField(upload_to='training/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
