# Generated by Django 5.2.6 on 2026-02-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatQuestion',
        ),
    ]
